function Layers = CNN_CCRCCRP_X3(Input_Size)
	
	Conv1_FilterSize = [2,2];
	Conv1_FiltersNum = 64;
	Padding_Vector = 'same'; % [1,1,1,1];
	
	%{
	Layers = [
			imageInputLayer([Input_Size,Input_Size,1]), ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,1,'Padding',Padding_Vector), ...
			regressionLayer];
	%}
	%
	Layers = [
			imageInputLayer([Input_Size,Input_Size,1]), ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), batchNormalizationLayer, reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), batchNormalizationLayer, reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), batchNormalizationLayer, reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), batchNormalizationLayer, reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), batchNormalizationLayer, reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), batchNormalizationLayer, reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), batchNormalizationLayer, reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), batchNormalizationLayer, reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), batchNormalizationLayer, reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), batchNormalizationLayer, reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), batchNormalizationLayer, reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), batchNormalizationLayer, reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), batchNormalizationLayer, reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), batchNormalizationLayer, reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), batchNormalizationLayer, reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), batchNormalizationLayer, reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), batchNormalizationLayer, reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), batchNormalizationLayer, reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), batchNormalizationLayer, reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), batchNormalizationLayer, reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), batchNormalizationLayer, reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), batchNormalizationLayer, reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum,'Padding',Padding_Vector), batchNormalizationLayer, reluLayer, ...
			convolution2dLayer(Conv1_FilterSize,1,'Padding',Padding_Vector), ...
			dropoutLayer(0.2), ...
			regressionLayer];
	%}
	
	%{
	Layers = [imageInputLayer([Input_Size,Input_Size,1]), ... % To left-right flip the inputs: 'DataAugmentation','randfliplr'
			  convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum),reluLayer, ...
			  convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum),reluLayer, ... % maxPooling2dLayer(2,'Stride',2), ...
			  convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum),reluLayer, ...
			  convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum),reluLayer, ... % maxPooling2dLayer(2,'Stride',2), ...
			  convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum),reluLayer, ...
			  convolution2dLayer(Conv1_FilterSize,Conv1_FiltersNum),reluLayer, ...
              regressionLayer];
			  
	%
			  fullyConnectedLayer([Input_Size,Input_Size,1]),reluLayer, ...
              fullyConnectedLayer([Input_Size,Input_Size,1]),reluLayer, ...
              fullyConnectedLayer([Input_Size,Input_Size,1]), ...
	%}
	
	%{
	Layers = [
		imageInputLayer([Input_Size,Input_Size,1]), ...
		convolution2dLayer(3,8,'Padding','same'), ...
		batchNormalizationLayer, ...
		reluLayer, ...
		averagePooling2dLayer(2,'Stride',2), ...
		convolution2dLayer(3,16,'Padding','same'), ...
		batchNormalizationLayer, ...
		reluLayer, ...
		averagePooling2dLayer(2,'Stride',2), ...
		convolution2dLayer(3,32,'Padding','same'), ...
		batchNormalizationLayer, ...
		reluLayer, ...
		convolution2dLayer(3,32,'Padding','same'), ...
		batchNormalizationLayer, ...
		reluLayer, ...
		dropoutLayer(0.2), ...
		fullyConnectedLayer(1), ...
		regressionLayer];
	%}
end