function Get_Menorah_Branches_Details(GUI_Parameters)
	
	[x,y] = ginput(1);
	
	MinD = max(size(GUI_Parameters.Workspace(1).Files{1}.Image0,1),size(GUI_Parameters.Workspace(1).Files{1}.Image0,2));
	C = 0;
	for i=1:numel(GUI_Parameters.Workspace(1).Files{1}.Branches)
		Xs = mean([GUI_Parameters.Workspace(1).Files{1}.Branches(i).Rectangles(1).X,GUI_Parameters.Workspace(1).Files{1}.Branches(i).Rectangles(end).X]);
		Ys = mean([GUI_Parameters.Workspace(1).Files{1}.Branches(i).Rectangles(1).Y,GUI_Parameters.Workspace(1).Files{1}.Branches(i).Rectangles(end).Y]);
		D = ((Xs - x)^2+(Ys - y)^2)^.5;
		if(D < MinD)
			MinD = D;
			C = i;
		end
	end
	
	TextBox = uicontrol(GUI_Parameters.Handles.Details_Tab,'style','text','Units','normalized','Position',[0,0,1,.8], ...
		'FontSize',18);
	set(TextBox,'BackgroundColor',get(GUI_Parameters.Handles.Details_Tab,'BackgroundColor'));
	set(TextBox,'String',['Length: ',num2str(GUI_Parameters.Workspace(1).Files{1}.Branches(C).Length), ...
		sprintf('\n \n'), ...
		'Width: ',num2str(GUI_Parameters.Workspace(1).Files{1}.Branches(C).Width), ...
		sprintf('\n \n'), ...
		'Curvature: ',num2str(GUI_Parameters.Workspace(1).Files{1}.Branches(C).Curvature), ...
		sprintf('\n \n'), ...
		'Line Angle: ',num2str(GUI_Parameters.Workspace(1).Files{1}.Branches(C).Line_Angle), ...
		sprintf('\n \n'), ...
		'Menorah Order: ',num2str(GUI_Parameters.Workspace(1).Files{1}.Branches(C).Order) ...
		]);
end