function Get_Segments_Details(GUI_Parameters)
	
	[x,y] = ginput(1);
	
	MinD = max(size(GUI_Parameters.Workspace(1).Files{1}.Image0,1),size(GUI_Parameters.Workspace(1).Files{1}.Image0,2));
	C = 0;
	for i=1:numel(GUI_Parameters.Workspace(1).Files{1}.Segments)
		Xs = mean([GUI_Parameters.Workspace(1).Files{1}.Segments(i).Rectangles(1).X,GUI_Parameters.Workspace(1).Files{1}.Segments(i).Rectangles(end).X]);
		Ys = mean([GUI_Parameters.Workspace(1).Files{1}.Segments(i).Rectangles(1).Y,GUI_Parameters.Workspace(1).Files{1}.Segments(i).Rectangles(end).Y]);
		D = ((Xs - x)^2+(Ys - y)^2)^.5;
		if(D < MinD)
			MinD = D;
			C = i;
		end
	end
	
	TextBox = uicontrol(GUI_Parameters.Handles.Details_Tab,'style','text','Units','normalized','Position',[0,0,1,.8], ...
		'FontSize',18,'HorizontalAlignment','left');
	set(TextBox,'BackgroundColor',get(GUI_Parameters.Handles.Details_Tab,'BackgroundColor'));
	set(TextBox,'String',['Length: ',num2str(GUI_Parameters.Workspace(1).Files{1}.Segments(C).Length), ...
		sprintf('\n \n'), ...
		'Width: ',num2str(GUI_Parameters.Workspace(1).Files{1}.Segments(C).Width), ...
		sprintf('\n \n'), ...
		'Line Angle: ',num2str(GUI_Parameters.Workspace(1).Files{1}.Segments(C).Line_Angle), ...
		sprintf('\n \n'), ...
		'Orientation: ',num2str(GUI_Parameters.Workspace(1).Files{1}.Segments(C).Orientation), ...
		sprintf('\n \n'), ...
		'Distance From Primary: ',num2str(mean([GUI_Parameters.Workspace(1).Files{1}.Segments(C).Rectangles.Distance_From_Primary])), ...
		sprintf('\n \n'), ...
		'Distance From CB: ',num2str(mean([GUI_Parameters.Workspace(1).Files{1}.Segments(C).Rectangles.Primary_Arc_Distance_From_CB])), ...
		sprintf('\n \n'), ...
		'Menorah Order: ',num2str(GUI_Parameters.Workspace(1).Files{1}.Segments(C).Order) ...
		]);
end